name: Refresh

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Refresh docs examples
      run: ${{ secrets.WEBHOOK_TRIGGERS }}

    - name: Slack notification
      uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "{workflow} workflow"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        footer: "<{workflow_url}|View Workflow>"
        notify_when: "failure"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
