name: Refresh

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Refresh docs examples
      run: ${{ secrets.WEBHOOK_TRIGGERS }}
